import { StageComponent } from 'aurelia-testing';
import { bootstrap } from 'aurelia-bootstrapper';
import { App } from '../../src/app';

describe('App', () => {
  // Dummy test to replace the autogenerated one
  it('says hello', () => {
    expect('Hello World!').toBe('Hello World!');
  });
});
